name: Run PyWard Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-pyward:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pyaes

    - name: Download and install pyward
      run: |
        package_url="https://github.com/geethaab/PyWard/raw/main/pyward-3.0.tar.gz"
        pip install "$package_url"

    - name: Run PyWard Script
      run: |
        python telegram-views-increaser.py
